### ISSUE TITLE
build-docker.sh sudo permissions to create text file 

### ISSUE THREAD

**Issue by mfobert** [aws-samples/easy-amazon-sagemaker-deployments#6]
Hi there, thanks for the library!

I noticed that build-docker.sh was not completing due to:
```
# Have to do this because pythons subprocess for calling this script does not wait for it to finish. Tried various args to Popen
sudo touch done.txt
```

Is there a reason you need superuser permission to create a text file?

Thanks,
Mark

**Comment by w601sxs** [comment]
was failing in some cases, but if you can test and do a PR I'll merge!
